apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    helm:
      valueFiles:
        - values-prod.yaml
    path: helm
    repoURL: 'https://github.com/Alrudin/nd064_course_1_project'
    targetRevision: HEAD